baseURL = "https://blog.markvincze.com/"
languageCode = "en-us"
title = "Mark Vincze"
theme = "pupintor"

# Enables Chroma-based syntax highlighting with theme "friendly"
# See https://xyproto.github.io/splash/docs/ for other theme options
pygmentsStyle = "friendly"
# If true, Chroma will highlight GitHub-style code fences in addition to
# highlight shortcodes
pygmentsCodeFences = true

# [params]
  # Enables the topmenu, which pulls from categories
  # topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Mark Vincze"
  github = "markvincze"
  email = "mrk.vincze@gmail.com"
  gaid = "Your Google Analytics ID"
  twitter = "mrkvincze"

[permalinks]
  posts = "/:title"