baseURL = "https://blog.markvincze.com/"
languageCode = "en-us"
title = "Mark Vincze"
theme = "pupintor"

[markup.highlight]
  style = "monokai"

[markup.goldmark.renderer]
  unsafe=true

[params]
  dateFormat = "Jan 2, 2006"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/cv.html"
    weight = 4
  # [[menu.main]]
  #   name = "Presentations"
  #   url = "/presentations"
  #   weight = 4
  # [[menu.main]]
  #   name = "Contact"
  #   url = "/contact"
  #   weight = 5

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:filename"