baseURL = "https://blog.markvincze.com/"
languageCode = "en-us"
title = "Mark Vincze"
theme = "pupintor"

[markup.highlight]
  style = "monokai"

[params]
  dateFormat = "Jan 2, 2006"
  # Enables the topmenu, which pulls from categories
  # topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

# [author]
#   name = "Mark Vincze"
#   github = "markvincze"
#   email = "mrk.vincze@gmail.com"
#   gaid = "Your Google Analytics ID"
#   twitter = "mrkvincze"

[permalinks]
  posts = "/:filename"